/*
 * Copyright (c) 2021 Twisted Palms Incorporated
 * All Rights Reserved.
 */

package dev.droppinganvil.v3.paypal;

import java.io.Serializable;

public enum EventType implements Serializable {
    //Payments
    PAYMENT_AUTHORIZATION_CREATED,
    PAYMENT_CAPTURE_COMPLETED,
    PAYMENT_SALE_COMPLETED,
    PAYMENT_SALE_DENIED,
    PAYMENT_SALE_PENDING,
    PAYMENT_SALE_REFUNDED,
    PAYMENT_SALE_REVERSED,
    //Subscriptions
    CATALOG_PRODUCT_CREATED,
    CATALOG_PRODUCT_UPDATED,
    BILLING_PLAN_CREATED,
    BILLING_PLAN_UPDATED,
    BILLING_PLAN_ACTIVATED,
    BILLING_PLAN_PRICING__CHANGE_ACTIVATED,
    BILLING_PLAN_DEACTIVATED,
    BILLING_SUBSCRIPTION_CREATED,
    BILLING_SUBSCRIPTION_ACTIVATED,
    BILLING_SUBSCRIPTION_UPDATED,
    BILLING_SUBSCRIPTION_EXPIRED,
    BILLING_SUBSCRIPTION_CANCELLED,
    BILLING_SUBSCRIPTION_SUSPENDED,
    BILLING_SUBSCRIPTION_PAYMENT_FAILED


}
